-- ============================================
-- Inventory Movements
-- ============================================

CREATE TABLE public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_variant_id BIGINT NOT NULL,

    type TEXT NOT NULL,

    quantity INTEGER NOT NULL,

    previous_quantity INTEGER NOT NULL,

    new_quantity INTEGER NOT NULL,

    reason TEXT,

    reference_type TEXT,

    reference_id BIGINT,

    created_by UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT inventory_movements_variant_fk
        FOREIGN KEY (product_variant_id)
        REFERENCES public.product_variants(id)
        ON DELETE RESTRICT,

    CONSTRAINT inventory_movements_created_by_fk
        FOREIGN KEY (created_by)
        REFERENCES public.users(id)
        ON DELETE SET NULL,

    CONSTRAINT inventory_movements_type_check
        CHECK (
            type IN (
                'sale',
                'restock',
                'manual_adjustment',
                'return',
                'cancellation'
            )
        ),

    CONSTRAINT inventory_movements_quantity_check
        CHECK (
            quantity <> 0
        ),

    CONSTRAINT inventory_movements_previous_quantity_check
        CHECK (
            previous_quantity >= 0
        ),

    CONSTRAINT inventory_movements_new_quantity_check
        CHECK (
            new_quantity >= 0
        )
);


-- ============================================
-- Indexes
-- ============================================

CREATE INDEX idx_inventory_movements_variant
ON public.inventory_movements(product_variant_id);

CREATE INDEX idx_inventory_movements_created_at
ON public.inventory_movements(created_at DESC);

CREATE INDEX idx_inventory_movements_type
ON public.inventory_movements(type);

CREATE INDEX idx_inventory_movements_reference
ON public.inventory_movements(
    reference_type,
    reference_id
);

CREATE INDEX idx_inventory_movements_created_by
ON public.inventory_movements(created_by);